// This file is automatically generated by qtc from "foo.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line foo.qtpl:1
package foobar

// plain

//line foo.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line foo.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line foo.qtpl:7
type bar interface {
	//line foo.qtpl:7
	Foo() string
	//line foo.qtpl:7
	StreamFoo(qw422016 *qt422016.Writer)
	//line foo.qtpl:7
	WriteFoo(qq422016 qtio422016.Writer)
//line foo.qtpl:7
}

//line foo.qtpl:12
var a = "foo"

//line foo.qtpl:15
func streamabc(qw422016 *qt422016.Writer) {
	//line foo.qtpl:15
	qw422016.N().S(`
	`)
	//line foo.qtpl:16
	qw422016.N().S(`Hello World
`)
	//line foo.qtpl:16
	qw422016.N().S(`
	`)
	//line foo.qtpl:17
	qw422016.E().S(math.complex(math.pi / 2))
	//line foo.qtpl:17
	qw422016.N().S(`
	`)
	//line foo.qtpl:18
	time.StreamNow(qw422016)
	//line foo.qtpl:18
	qw422016.N().S(`
	%}
`)
//line foo.qtpl:20
}

//line foo.qtpl:20
func writeabc(qq422016 qtio422016.Writer) {
	//line foo.qtpl:20
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line foo.qtpl:20
	streamabc(qw422016)
	//line foo.qtpl:20
	qt422016.ReleaseWriter(qw422016)
//line foo.qtpl:20
}

//line foo.qtpl:20
func abc() string {
	//line foo.qtpl:20
	qb422016 := qt422016.AcquireByteBuffer()
	//line foo.qtpl:20
	writeabc(qb422016)
	//line foo.qtpl:20
	qs422016 := string(qb422016.B)
	//line foo.qtpl:20
	qt422016.ReleaseByteBuffer(qb422016)
	//line foo.qtpl:20
	return qs422016
//line foo.qtpl:20
}
